### ISSUE TITLE
Renumber fails if the goal label is a number

### ISSUE THREAD

**Issue by BTernaryTau** [expln/metamath-lamp#207] opened 2024-10-16 17:36 UTC
If the label for the goal statement is a number, attempting to renumber steps will fail with the error `Cannot renumber steps: there was an internal error during renumbering.`

This case doesn't necessarily need to be supported by the renumber option, but there should probably be a more specific error message at the very least.

<img width="950" alt="image" src="https://github.com/user-attachments/assets/d89e8c1c-0f6f-406c-be54-d80ef1815f1f">

**Comment by expln** [comment] 2024-10-17 10:26
Thanks for reporting this issue. It is fixed on [dev](https://expln.github.io/lamp/dev/index.html). The fix was to exclude the goal step from automatic renumbering. The goal step is a special one, so users should manage its label manually. The error message was also improved, but it still will not show the exact root cause. It is not possible due to how renumbering is implemented. 


The renumbering works in two stages: 1 - renumber using a special renumbering algorithm; 2 - check there are no errors in the editor after renumbering. If there are errors then renumbering results are discarded. The special renumbering algorithm is supposed to respect the rules checked on the second stage. But this may not always be true due to a bug in the code. For example, there is a rule that hypothesis steps and the goal step must have labels which don’t clash with symbols existing  in the loaded context (because these labels will appear in the final proof which is supposed to be copy-pasted to the MM database). Before the fix, the goal step was renamed to `1`. But there is such a constant in set.mm. Therefore this was an illegal label for the goal step. With the improved error message you would see the following (it is not possible to reproduce after the fix has been applied):


![image](https://github.com/user-attachments/assets/8c72fdb8-d6c0-4308-94d7-b3d2472c8873)

It is still not absolutely clear from this message why renumbering failed, but at least it points out to the statement `|- ph` and this may give the user some clue of what to look into (I guess you spent some time trying to find out the root cause when you faced this error for the first time).

**Comment by expln** [comment] 2024-11-02 10:40
The fix is available in [version 25](https://expln.github.io/lamp/v25/index.html).

**Closed by expln** 2024-11-02 10:40 UTC
Labels: bug, ready-on-dev
